openapi: 3.0.2
info:
  title: Pedagogical Consultant Service API
  version: "1.0"
servers:
  - url: http://api.babies360.com/v1
    description: production server
  - url: http://localhost:9091/
    description: dev server
paths:
  /consultants:
    get:
      summary: Retrieve the list of consultants in a specific zone
      parameters:
        - in: query
          name: zone
          schema:
            type: string
          required: true
          description: Zone of interest
          example: Naples
      responses:
        "200":
          description: The list of consultants in the requested zone
          content:
            application/json:
              schema:
                type: object
                properties:
                  consultants:
                    type: array
                    items:
                      $ref: "#/components/schemas/Consultant"
                  message:
                    type: string
  
  /consultants/{id}:
    get:
      summary: Retrieve a specific consultant's profile
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Consultant's email
          example: b.rossi@mail.it
      responses:
        "200":
          description: Consultant's profile
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Consultant"

components:
  schemas:
    Consultant:
      type: object
      properties:
        name:
          type: string
        surname:
          type: string
        address:
          type: string
        phone:
          type: string
        email:
          type: string
        city:
          type: string
      example:
        name: Bianca
        surname: Rossi
        address: Via Roma 1
        phone: "+3934567890"
        email: b.rossi@mail.it
        city: Rome
