openapi: "3.0.2"
info:
  title: Babysitting Service API
  version: "1.0"
servers:
  - url: http://api.babies360.com/v1
    description: production server
  - url: http://localhost:9090/
    description: dev server

paths:
  /babysitters:
    get:
      summary: Fetch the babysitters available for specific parameters
      parameters:
        - name: date
          in: query
          required: true
          schema:
            type: string
            format: date
          description: Date in which the babysitter is needed
          example: "1" # for now we use a single digit for the day of the week
        - name: starttime
          in: query
          required: true
          schema:
            type: string
            format: time
          description: Start time of the babysitting service
          example: "9:00"
        - name: numofhours
          in: query
          required: true
          schema:
            type: integer
            minimum: 1
          description: Number of hours of the babysitting service
          example: 3
        - name: city
          in: query
          required: true
          schema:
            type: string
          description: City where the babysitter is needed
          example: Milan
        - name: numofchildren
          in: query
          required: true
          schema:
            type: integer
            minimum: 1
          description: Number of children to babysit
          example: 2
        - name: requestedservices
          in: query
          required: true
          schema:
            type: array
            items:
              type: string
          description: Services requested by the parents
          example: ["homework_help", "pick_up", "keep_company", "play"]
      responses:
        "200":
          description: List of available babysitters with profiles and availability
        "400":
          description: Bad request, parameters are missing or invalid
  
  /babysitters/{id}:
    get:
      summary: View babysitter profile
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Babysitter email
          example: bianca@mail.it
      responses:
        "200":
          description: Detailed profile of the babysitter
        "400":
          description: Bad request, parameters are missing or invalid
        "404":
          description: Babysitter profile not found
  
  /babysitters/booking:
    post:
      summary: Select a babysitter and proceed to payment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                babysitterId:
                  type: string
                date:
                  type: string
                time:
                  type: string
              example:
                babysitterId: bianca@mail.it
                date: "1"
                time: "9:00"
      responses:
        "200":
          description: Payment portal and confirmation of booking upon successful payment
        "400":
          description: Bad request, parameters are missing or invalid
        "404":
          description: Babysitter not found

  /babysitters/register:
    post:
      summary: Register as a babysitter
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Babysitter'
      responses:
        "200":
          description: Registration successful
        "400":
          description: Bad request, a babysitter with that email already exists
        "500":
          description: Internal server error

  /babysitters/update-availabilities:
    put:
      summary: Update babysitter availabilities
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                babysitter_email:
                  type: string
                availabilities:
                  type: array
                  items:
                    type: object
              example:
                babysitter_email: bianca@mail.it
                availabilities: [
                  {
                    "day": "1",
                    "is_available": "false",
                  },
                  {
                    "day": "2",
                    "is_available": "true",
                  },
                  {
                    "day": "3",
                    "is_available": "false",
                  },
                  {
                    "day": "4",
                    "is_available": "true",
                  },
                  {
                    "day": "5",
                    "is_available": "true",
                  },
                  {
                    "day": "6",
                    "is_available": "false",
                  },
                  {
                    "day": "7",
                    "is_available": "false",
                  }
                ]
      responses:
        "200":
          description: Availabilities updated successfully
        "400":
          description: Bad request, parameters are missing or invalid
        "404":
          description: Babysitter not found
        "500":
          description: Internal server error

components:
  schemas:
    Babysitter:
      type: object
      properties:
        name:
          type: string
        surname:
          type: string
        email:
          type: string
          format: email
        city:
          type: string
        postal_code:
          type: string
        phone:
          type: string
        services:
          type: array
          items:
            type: string
        hourly_salary:
          type: number
        availabilities:
          type: array
          items:
            type: object
      example:
        name: Bianca
        surname: Rossi
        email: bianca@mail.it
        city: Milan
        postal_code: "20133"
        phone: "+4930664040900"
        services: ["homework_help", "pick_up"]
        hourly_salary: 10