openapi: "3.0.2"
info:
  title: Babysitting Service API
  version: "1.0"
servers:
  - url: http://api.babies360.com/v1
    description: production server
  - url: http://localhost:9090/
    description: dev server

paths:
  /babysitters:
    get:
      summary: Query available babysitters for a specific date and time
      parameters:
        - name: date
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: starttime
          in: query
          required: true
          schema:
            type: string
            format: time
        - name: numofhours
          in: query
          required: true
          schema:
            type: integer
        - name: city
          in: query
          required: true
          schema:
            type: string
        - name: numofchildren
          in: query
          required: true
          schema:
            type: integer
        - name: requestedservices
          in: query
          required: true
          schema:
            type: array
            items:
              type: string
      responses:
        "200":
          description: List of available babysitters with profiles and availability
        "400":
          description: Bad request, parameters are missing or invalid
  
  /babysitters/{id}:
    get:
      summary: View babysitter profile and ratings
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Detailed profile of the babysitter including ratings and reviews
        "400":
          description: Bad request, parameters are missing or invalid
        "404":
          description: Babysitter not found
  
  /babysitters/booking:
    post:
      summary: Select a babysitter and proceed to payment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                babysitterId:
                  type: string
                date:
                  type: string
                time:
                  type: string
      responses:
        "200":
          description: Payment portal and confirmation of booking upon successful payment
        "400":
          description: Bad request, parameters are missing or invalid
        "404":
          description: Babysitter not found

  /babysitters/register:
    post:
      summary: Register as a babysitter
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                surname:
                  type: string
                email:
                  type: string
                  format: email
                city:
                  type: string
                postal_code:
                  type: string
                phone:
                  type: string
                services:
                  type: array
                  items:
                    type: string
                hourly_salary:
                  type: number
                availabilities:
                  type: array
                  items:
                    type: object
      responses:
        "200":
          description: Registration successful
        "400":
          description: Bad request, a babysitter with that email already exists
        "500":
          description: Internal server error

  /babysitters/update-availabilities:
    # update babysitter availabilities
    put:
      summary: Update babysitter availabilities
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                babysitter_email:
                  type: string
                availabilities:
                  type: array
                  items:
                    type: object
      responses:
        "200":
          description: Availabilities updated successfully
        "400":
          description: Bad request, parameters are missing or invalid
        "404":
          description: Babysitter not found
        "500":
          description: Internal server error