openapi: "3.0.2"
info:
  title: Party Organizer Service API
  version: "1.0"
servers:
  - url: http://api.babies360.com/v1
    description: production server
  - url: http://localhost:9092/
    description: dev server
paths:
  
  /party-plan:
    get:
      summary: Get proposal for party services based on user preferences
      parameters:
        - name: date
          in: query
          schema:
            type: string
          required: true
          example: "Wednesday"
        - name: location
          in: query
          schema:
            type: string
          required: true
          example: Milan
        - name: requestedservices
          in: query
          schema:
            type: array
            items:
              type: string
          required: true
          example: ["decorations", "catering", "entertainment", "dj", "bus_service"]
        - name: budget
          in: query
          schema:
            type: string
          required: true
          example: "Wednesday"
      responses:
        "200":
          description: Available vendor/s for each specified party option
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VendorsProposals'

  /proposal-selection:
    post:
      summary: Send to party planner the selected option for each category
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: "Confirmation of selection and scheduling of services"
        "400":
          description: "Bad request, parameters are missing or invalid"

components:
  schemas:
    VendorsProposals:
      type: object
      properties:
        catering:
          type: array
          items:
            type: string
        decorations:
          type: array
          items:
            type: string
        entertainment:
          type: array
          items:
            type: string
        dj:
          type: array
          items:
            type: string
        bus_service:
          type: array
          items:
            type: string