openapi: "3.0.2"
info:
  title: party Service API
  version: "1.0"
servers:
  - url: http://api.babies360.com/v1
    description: production server
  - url: http://localhost:9092/
    description: dev server
paths:
  
  /party-plan:
    get:
      summary: Get proposal for party services based on user preferences
      parameters:
        - in: query
          name: date
          schema:
            type: string
          required: true
        - in: query
          name: location
          schema:
            type: string
          required: true
        - in: query
          name: options
          schema:
            type: array
            items:
              type: string
          required: true
        - in: query
          name: budget
          schema:
            type: string
          required: true
      responses:
        "200":
          description: Available vendor for each specified party option
          content:
            application/json:
              schema:
                type: object
                properties:
                  catering:
                    type: array
                    items:
                      type: string
                  balloons:
                    type: array
                    items:
                      type: string
                  entertainment:
                    type: array
                    items:
                      type: string
                  dj:
                    type: array
                    items:
                      type: string
                  bus_service:
                    type: array
                    items:
                      type: string

  /proposal-selection:
    post:
      summary: Send to party planner the selected option for each category
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: "Confirmation of selection and scheduling of services"
        "400":
          description: "Bad request, parameters are missing or invalid"
